---
name: Lint Code Base
on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter/slim@v4
        
        env:
          SUPPRESS_POSSUM: true
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false